"""
Please create a python question that ask student to write a python
program which allow user to input a increment for each while loop
from 1 to 100

increment = int( input( 'Enter a positive increment value: ' ) )

1. Prompt the user to input a positive integer to use as the increment.
2. Ensure the input is a positive integer. If not, display an error message and prompt again.
3. Use a while loop to iterate from 1 to 100, incrementing by the user's input.
4. Print each number generated by the loop.
"""

# Get the initial increment value from user
increment = int(input('Enter a positive increment value: '))

# Input validation loop: ensure the increment is positive
while increment <= 0:
    print("Error: Please enter a positive value!!")
    increment = int(input('Enter a positive increment value: '))

# Initialize the starting number
number = 1

# Main loop: print numbers from 1 to 100 using the increment
while number <= 100:
    print(number)
    number += increment  # Add the increment to get the next number
