"""
Please create a python question that ask student to write a python
program which allow user to input a increment for each while loop
from 1 to 100

increment = int( input( 'Enter a positive increment value: ' ) )

1. Prompt the user to input a positive integer to use as the increment.
2. Ensure the input is a positive integer. If not, display an error message and prompt again.
3. Use a while loop to iterate from 1 to 100, incrementing by the user's input.
4. Print each number generated by the loop.
"""


increment = int( input( 'Enter a positive increment value: ' ) )

while increment <= 0:
    print("Error: Please enter a positive value!!")
    increment = int( input( 'Enter a positive increment value: ' ) )

number = 1

while number <=100:
    print(number)
    number += increment
